// Copyright (c) Krosmoz 2025.
// Krosmoz licenses this file to you under the MIT license.
// See the license here https://github.com/AerafalGit/Krosmoz/blob/main/LICENSE.

namespace Krosmoz.Protocol.Enums.Custom;

public enum OrnamentIds
{
	Niveau100 = 13,
	Niveau160 = 14,
	Niveau200 = 15,
	ScoreHonorable = 16,
	ScoreRespectable = 17,
	ScoreImposant = 18,
	ExplorateurHonorable = 19,
	BaroudeurHonorable = 22,
	BaroudeurRespectable = 23,
	BaroudeurImposant = 24,
	BaroudeurVenerable = 25,
	Vigilant = 26,
	BatailleurHonorable = 27,
	BatailleurRespectable = 28,
	BatailleurImposant = 29,
	BatailleurVenerable = 30,
	BagarreurImposant = 31,
	BagarreurHonorable = 32,
	BagarreurRespectable = 33,
	ChalongeurHonorable = 34,
	ChalongeurRespectable = 35,
	FloconHonorable = 36,
	FloconRespectable = 37,
	FloconImposant = 38,
	AventurierHonorable = 39,
	AventurierRespectable = 40,
	AventurierImposant = 41,
	DegivreurHonorable = 42,
	DegivreurRespectable = 43,
	DegivreurImposant = 44,
	ArtisanHonorable = 45,
	DragomaitreHonorable = 46,
	DragomaitreRespectable = 47,
	DragomaitreImposant = 48,
	BaroudeurGlorieux = 49,
	BaroudeurEminent = 50,
	BatailleurGlorieux = 51,
	VulkanologueHonorable = 52,
	Cawotteur = 55,
	Justicier = 56,
	Queteur = 57,
	VisiteurDEnutrosor = 58,
	VisiteurDeSrambad = 59,
	ScoreRemarquable = 60,
	VisiteurDuXelorium = 61,
	CoeurVaillantHonorable = 62,
	CoeurVaillantRespectable = 63,
	EspritSalvateurHonorable = 67,
	EspritSalvateurRespectable = 68,
	OEilAttentifHonorable = 72,
	OEilAttentifRespectable = 73,
	CoeurSaignantHonorable = 77,
	CoeurSaignantRespectable = 78,
	EspritMalsainHonorable = 82,
	EspritMalsainRespectable = 83,
	OEilPutrideHonorable = 87,
	OEilPutrideRespectable = 88,
	ScoreVenerable = 92,
	IdoleHonorable = 94,
	IdoleRespectable = 95,
	IdoleVenerable = 96,
	IdoleImposante = 97,
	IdoleGlorieuse = 98,
}
