// <auto-generated />
using System;
using System.Net;
using System.Net.NetworkInformation;
using Krosmoz.Servers.AuthServer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Krosmoz.Servers.AuthServer.Database.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20250608123749_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Krosmoz.Servers.AuthServer.Database.Models.Accounts.AccountRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Hierarchy")
                        .HasColumnType("integer");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet");

                    b.Property<PhysicalAddress>("MacAddress")
                        .HasColumnType("macaddr");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecretAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecretQuestion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubscriptionExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SubscriptionStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Ticket")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.UseCollation(b.HasIndex("Nickname"), new[] { "case_insensitive" });

                    b.HasIndex("Ticket")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 1, 13, 24, 16, 8, DateTimeKind.Utc),
                            Hierarchy = 40,
                            Password = "21232f297a57a5a743894a0e4a801fc3",
                            SecretAnswer = "blue",
                            SecretQuestion = "What is your favorite color?",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Krosmoz.Servers.AuthServer.Database.Models.Accounts.Activities.AccountActivityRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<IPAddress>("IpAddress")
                        .IsRequired()
                        .HasColumnType("inet");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("accounts_activities", (string)null);
                });

            modelBuilder.Entity("Krosmoz.Servers.AuthServer.Database.Models.Accounts.Characters.AccountCharacterRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("integer");

                    b.Property<int>("CharacterId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ServerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ServerId");

                    b.ToTable("accounts_characters", (string)null);
                });

            modelBuilder.Entity("Krosmoz.Servers.AuthServer.Database.Models.Accounts.Relations.AccountRelationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("RelationType")
                        .HasColumnType("integer");

                    b.Property<int>("ToAccountId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromAccountId");

                    b.ToTable("accounts_relations", (string)null);
                });

            modelBuilder.Entity("Krosmoz.Servers.AuthServer.Database.Models.Banishments.BanishmentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet");

                    b.Property<PhysicalAddress>("MacAddress")
                        .HasColumnType("macaddr");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("banishments", (string)null);
                });

            modelBuilder.Entity("Krosmoz.Servers.AuthServer.Database.Models.Servers.ServerRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("Community")
                        .HasColumnType("integer");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet");

                    b.Property<int>("JoinableHierarchy")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Port")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("VisibleHierarchy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("servers", (string)null);
                });

            modelBuilder.Entity("Krosmoz.Servers.AuthServer.Database.Models.Accounts.Activities.AccountActivityRecord", b =>
                {
                    b.HasOne("Krosmoz.Servers.AuthServer.Database.Models.Accounts.AccountRecord", null)
                        .WithOne("Activity")
                        .HasForeignKey("Krosmoz.Servers.AuthServer.Database.Models.Accounts.Activities.AccountActivityRecord", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Krosmoz.Servers.AuthServer.Database.Models.Accounts.Characters.AccountCharacterRecord", b =>
                {
                    b.HasOne("Krosmoz.Servers.AuthServer.Database.Models.Accounts.AccountRecord", null)
                        .WithMany("Characters")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Krosmoz.Servers.AuthServer.Database.Models.Accounts.Relations.AccountRelationRecord", b =>
                {
                    b.HasOne("Krosmoz.Servers.AuthServer.Database.Models.Accounts.AccountRecord", null)
                        .WithMany("Relations")
                        .HasForeignKey("FromAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Krosmoz.Servers.AuthServer.Database.Models.Accounts.AccountRecord", b =>
                {
                    b.Navigation("Activity");

                    b.Navigation("Characters");

                    b.Navigation("Relations");
                });
#pragma warning restore 612, 618
        }
    }
}
