// Copyright (c) Krosmoz 2025.
// Krosmoz licenses this file to you under the MIT license.
// See the license here https://github.com/AerafalGit/Krosmoz/blob/main/LICENSE.

using System.Collections.Immutable;
using Krosmoz.SourceGenerators.Infrastructure;
using Krosmoz.SourceGenerators.Infrastructure.Extensions;
using Krosmoz.SourceGenerators.MessageHandler.Models;
using Microsoft.CodeAnalysis;

namespace Krosmoz.SourceGenerators.MessageHandler;

public sealed partial class MessageHandlerSourceGenerator
{
    /// <summary>
    /// Generates source code based on the provided message handler symbols and assembly type.
    /// </summary>
    /// <param name="context">The context for source production, used to report diagnostics and add generated sources.</param>
    /// <param name="symbols">An immutable array of <see cref="MessageHandlerSymbol"/> representing the message handler symbols to process.</param>
    /// <param name="isAuthAssembly">
    /// A boolean value indicating whether the assembly being processed is an authentication assembly.
    /// </param>
    private static void Generate(SourceProductionContext context, ImmutableArray<MessageHandlerSymbol> symbols, bool isAuthAssembly)
    {
        var serverName = isAuthAssembly ? "Auth" : "Game";

        GenerateMessageDispatcher(context, symbols, serverName);
        GenerateServiceCollectionExtensions(context, symbols, serverName);
    }

    /// <summary>
    /// Generates a source file containing extension methods for registering message handlers
    /// in the dependency injection container.
    /// </summary>
    /// <param name="context">The context for source production, used to add the generated source file.</param>
    /// <param name="symbols">An immutable array of <see cref="MessageHandlerSymbol"/> representing the message handler symbols to process.</param>
    /// <param name="serverName">The name of the server (e.g., "Auth" or "Game") for which the extensions are being generated.</param>
    private static void GenerateServiceCollectionExtensions(SourceProductionContext context, ImmutableArray<MessageHandlerSymbol> symbols, string serverName)
    {
        var builder = new IndentedStringBuilder()
            .AppendLine("// <auto-generated/>")
            .AppendLine()
            .AppendLine("// Copyright (c) Krosmoz 2025.")
            .AppendLine("// Krosmoz licenses this file to you under the MIT license.")
            .AppendLine("// See the license here https://github.com/AerafalGit/Krosmoz/blob/main/LICENSE.")
            .AppendLine()
            .AppendLine("using Microsoft.Extensions.DependencyInjection;")
            .AppendLine("using Krosmoz.Servers.{0}Server.Network.Dispatcher.Handlers;", serverName)
            .AppendLine()
            .AppendLine("namespace Krosmoz.Servers.{0}Server.Extensions;", serverName)
            .AppendLine()
            .AppendLine("/// <summary>")
            .AppendLine("/// Provides extension methods for registering message handlers in the dependency injection container.")
            .AppendLine("/// </summary>")
            .AppendLine("public static class {0}MessageHandlerServiceCollectionExtensions", serverName);

        using (builder.CreateScope())
        {
            builder
                .AppendIndentedLine("/// <summary>")
                .AppendIndentedLine("/// Adds message handlers to the specified <see cref=\"IServiceCollection\"/>.")
                .AppendIndentedLine("/// </summary>")
                .AppendIndentedLine("/// <param name=\"services\">The <see cref=\"IServiceCollection\"/> to which the message handlers will be added.</param>")
                .AppendIndentedLine("/// <returns>The updated <see cref=\"IServiceCollection\"/> with the registered message handlers.</returns>")
                .AppendIndentedLine("public static IServiceCollection AddMessageHandlers(this IServiceCollection services)");

            using (builder.CreateScope())
            {
                builder
                    .AppendIndentedLine("return services")
                    .Indent()
                    .AppendIndentedLine(".AddSingleton<global::Krosmoz.Core.Network.Dispatcher.IMessageDispatcher<global::Krosmoz.Core.Network.Protocol.Dofus.DofusMessage>, global::Krosmoz.Servers.{0}Server.Network.Dispatcher.{0}MessageDispatcher>()", serverName);

                foreach (var (index, (handlerName, messageName)) in symbols.Index())
                    builder.AppendIndentedLine(".AddSingleton<{0}MessageHandler<{1}>, {2}>(){3}", serverName, messageName, handlerName, index == symbols.Length - 1 ? ";" : string.Empty);

                builder.Unindent();
            }
        }

        context.AddSource($"{serverName}MessageHandlerServiceCollectionExtensions.g.cs", builder.ToString());
    }

    /// <summary>
    /// Generates a source file for a message dispatcher class based on the provided symbols and server name.
    /// </summary>
    /// <param name="context">The context for source production, used to add the generated source file.</param>
    /// <param name="symbols">An immutable array of <see cref="MessageHandlerSymbol"/> representing the message handler symbols to process.</param>
    /// <param name="serverName">The name of the server (e.g., "Auth" or "Game") for which the dispatcher is being generated.</param>
    private static void GenerateMessageDispatcher(SourceProductionContext context, ImmutableArray<MessageHandlerSymbol> symbols, string serverName)
    {
        var builder = new IndentedStringBuilder()
            .AppendLine("// <auto-generated/>")
            .AppendLine()
            .AppendLine("// Copyright (c) Krosmoz 2025.")
            .AppendLine("// Krosmoz licenses this file to you under the MIT license.")
            .AppendLine("// See the license here https://github.com/AerafalGit/Krosmoz/blob/main/LICENSE.")
            .AppendLine()
            .AppendLine("using Microsoft.Extensions.DependencyInjection;")
            .AppendLine("using Krosmoz.Core.Network.Dispatcher;")
            .AppendLine("using Krosmoz.Core.Network.Protocol.Dofus;")
            .AppendLine("using Krosmoz.Core.Network.Transport;")
            .AppendLine("using Krosmoz.Servers.{0}Server.Network.Dispatcher.Handlers;", serverName)
            .AppendLine("using Krosmoz.Servers.{0}Server.Network.Transport;", serverName)
            .AppendLine()
            .AppendLine("namespace Krosmoz.Servers.{0}Server.Network.Dispatcher;", serverName)
            .AppendLine()
            .AppendLine("/// <inheritdoc />")
            .AppendLine("public sealed class {0}MessageDispatcher : IMessageDispatcher<DofusMessage>", serverName);

        using (builder.CreateScope())
        {
            builder
                .AppendIndentedLine("private readonly IServiceProvider _services;")
                .AppendLine()
                .AppendIndentedLine("/// <summary>")
                .AppendIndentedLine("/// Initializes a new instance of the <see cref=\"{0}MessageDispatcher\"/> class.", serverName)
                .AppendIndentedLine("/// </summary>")
                .AppendIndentedLine("/// <param name=\"services\">The <see cref=\"IServiceProvider\"/> to use for resolving message handlers.</param>")
                .AppendIndentedLine("public {0}MessageDispatcher(IServiceProvider services)", serverName);

            using (builder.CreateScope())
                builder.AppendIndentedLine("_services = services;");

            builder
                .AppendLine()
                .AppendIndentedLine("/// <inheritdoc />")
                .AppendIndentedLine("public Task DispatchMessageAsync(TcpSession<DofusMessage> session, DofusMessage message)");

            using (builder.CreateScope())
            {
                builder
                    .AppendIndentedLine("if (session is not {0}Session typedSession)", serverName)
                    .Indent()
                    .AppendIndentedLine("throw new ArgumentException(\"Session is not of type {0}Session\", nameof(session));", serverName)
                    .Unindent()
                    .AppendLine()
                    .AppendIndentedLine("return message.ProtocolId switch")
                    .AppendIndentedLine('{')
                    .Indent();

                foreach (var (_, messageTypeName) in symbols)
                    builder.AppendIndentedLine("{0}.StaticProtocolId => _services.GetRequiredService<{1}MessageHandler<{2}>>().HandleAsync(typedSession, ({3})message),", messageTypeName, serverName, messageTypeName, messageTypeName);

                builder
                    .AppendIndentedLine("_ => Task.CompletedTask")
                    .Unindent()
                    .AppendIndentedLine("};");
            }
        }

        context.AddSource($"{serverName}MessageDispatcher.g.cs", builder.ToString());
    }
}
