// <auto-generated />
using Krosmoz.Servers.GameServer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Krosmoz.Servers.GameServer.Database.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:case_insensitive", "en-u-ks-primary,en-u-ks-primary,icu,False")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Krosmoz.Servers.GameServer.Database.Models.Experiences.ExperienceRecord", b =>
                {
                    b.Property<byte>("Level")
                        .HasColumnType("smallint");

                    b.Property<long?>("AlignmentHonor")
                        .HasColumnType("bigint");

                    b.Property<long>("CharacterXp")
                        .HasColumnType("bigint");

                    b.Property<long>("GuildXp")
                        .HasColumnType("bigint");

                    b.Property<long?>("JobXp")
                        .HasColumnType("bigint");

                    b.Property<long?>("MountXp")
                        .HasColumnType("bigint");

                    b.HasKey("Level");

                    b.ToTable("experiences", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
